require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/catagories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Catagory. As you add validations to Catagory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Catagory.create! valid_attributes
      get catagories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      catagory = Catagory.create! valid_attributes
      get catagory_url(catagory)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_catagory_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      catagory = Catagory.create! valid_attributes
      get edit_catagory_url(catagory)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Catagory" do
        expect {
          post catagories_url, params: { catagory: valid_attributes }
        }.to change(Catagory, :count).by(1)
      end

      it "redirects to the created catagory" do
        post catagories_url, params: { catagory: valid_attributes }
        expect(response).to redirect_to(catagory_url(Catagory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Catagory" do
        expect {
          post catagories_url, params: { catagory: invalid_attributes }
        }.to change(Catagory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post catagories_url, params: { catagory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested catagory" do
        catagory = Catagory.create! valid_attributes
        patch catagory_url(catagory), params: { catagory: new_attributes }
        catagory.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the catagory" do
        catagory = Catagory.create! valid_attributes
        patch catagory_url(catagory), params: { catagory: new_attributes }
        catagory.reload
        expect(response).to redirect_to(catagory_url(catagory))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        catagory = Catagory.create! valid_attributes
        patch catagory_url(catagory), params: { catagory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested catagory" do
      catagory = Catagory.create! valid_attributes
      expect {
        delete catagory_url(catagory)
      }.to change(Catagory, :count).by(-1)
    end

    it "redirects to the catagories list" do
      catagory = Catagory.create! valid_attributes
      delete catagory_url(catagory)
      expect(response).to redirect_to(catagories_url)
    end
  end
end
